In [4]:
import tensorflow as tf

In [5]:
# File path to save the data
save_file = './model.ckpt'



In [6]:
# Two tensor variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2,3]))
bias = tf.Variable(tf.truncated_normal([3]))

In [7]:
# Class used to save or restore tensor variables
saver = tf.train.Saver()

In [8]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print('weights: ')
    print(sess.run(weights))
    print('bias: ')
    print(sess.run(bias))
    
    # save the model
    saver.save(sess,save_file)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
weights: 
[[ 0.13989881 -0.78892213 -1.97327554]
 [ 0.05015963  0.78779256  0.02008943]]
bias: 
[ 0.5564127  -0.3817403  -0.54364806]


The Tensors weights and bias are set to random values using the tf.truncated_normal() function. The values are then saved to the save_file location, "model.ckpt", using the tf.train.Saver.save() function. (The ".ckpt" extension stands for "checkpoint".)

If you're using TensorFlow 0.11.0RC1 or newer, a file called "model.ckpt.meta" will also be created. This file contains the TensorFlow graph.

# Loading Variables

#### Now that tensor variable are saved, lets load them back into new model

In [9]:
# Remove the previous weights and bias
tf.reset_default_graph()

In [10]:

weights = tf.Variable(tf.truncated_normal([2,3]))
bias = tf.Variable(tf.truncated_normal([3]))

In [11]:
saver = tf.train.Saver()

In [12]:
with tf.Session() as sess:
    # load the weights and bias
    saver.restore(sess,save_file)
    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

Weight:
[[ 0.13989881 -0.78892213 -1.97327554]
 [ 0.05015963  0.78779256  0.02008943]]
Bias:
[ 0.5564127  -0.3817403  -0.54364806]


# Save a trained model 

Let's see how to train a model and save its weights.

First start with a model:

In [13]:
tf.reset_default_graph()

In [14]:
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

In [15]:
# Import MNIST data
mnist = input_data.read_data_sets('/Users/omarfaroque/tensorflow-master/tensorflow/examples/udacity', one_hot=True)

Extracting /Users/omarfaroque/tensorflow-master/tensorflow/examples/udacity/train-images-idx3-ubyte.gz
Extracting /Users/omarfaroque/tensorflow-master/tensorflow/examples/udacity/train-labels-idx1-ubyte.gz
Extracting /Users/omarfaroque/tensorflow-master/tensorflow/examples/udacity/t10k-images-idx3-ubyte.gz
Extracting /Users/omarfaroque/tensorflow-master/tensorflow/examples/udacity/t10k-labels-idx1-ubyte.gz


In [16]:
learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

In [17]:
# Features and Labels
features = tf.placeholder(tf.float32,[None,n_input])
labels = tf.placeholder(tf.float32,[None,n_classes])


In [18]:
# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

In [19]:
# Logits - xw+b
logits = tf.add(tf.matmul(features,weights),bias)

In [20]:
# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

In [21]:
# calculate accuracy 
correct_prediction = tf.equal(tf.arg_max(logits,1),tf.arg_max(labels,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [22]:
import math

save_file = './train_model.ckpt'
batch_size = 128
n_epochs = 100

In [23]:
saver = tf.train.Saver()

In [34]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # Training cycle
    for epoch in range(n_epochs):
        total_batch = math.ceil(mnist.train.num_examples / batch_size)

        # Loop over all batches
        for i in range(100):
            batch_features, batch_labels = mnist.train.next_batch(batch_size)
            sess.run(
                optimizer,
                feed_dict={features: batch_features, labels: batch_labels})

        # Print status for every 10 epochs
        if epoch % 10 == 0:
            valid_accuracy = sess.run(
                accuracy,
                feed_dict={
                    features: mnist.validation.images,
                    labels: mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy: {}'.format(
                epoch,
                valid_accuracy))

    # Save the model
    saver.save(sess, save_file)
    print('Trained Model Saved.')
    

            

Epoch 0   - Validation Accuracy: 0.0882000029087
Epoch 10  - Validation Accuracy: 0.103200003505
Epoch 20  - Validation Accuracy: 0.140200003982
Epoch 30  - Validation Accuracy: 0.183599993587
Epoch 40  - Validation Accuracy: 0.227799996734
Epoch 50  - Validation Accuracy: 0.272399991751
Epoch 60  - Validation Accuracy: 0.316399991512
Epoch 70  - Validation Accuracy: 0.355800002813
Epoch 80  - Validation Accuracy: 0.38299998641
Epoch 90  - Validation Accuracy: 0.411599993706
Trained Model Saved.


# Load a Trained Model

In [35]:
saver = tf.train.Saver()

# Launch the graph
with tf.Session() as sess:
    saver.restore(sess, save_file)

    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: mnist.test.images, labels: mnist.test.labels})

print('Test Accuracy: {}'.format(test_accuracy))

Test Accuracy: 0.449699997902
